# Generated by Django 2.2.4 on 2019-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoDivisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto_nome', models.CharField(max_length=255, unique=True)),
                ('assunto_desc', models.TextField()),
            ],
            options={
                'db_table': 'assunto_divisao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssuntoSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto_nome', models.CharField(max_length=255, unique=True)),
                ('assunto_desc', models.TextField()),
            ],
            options={
                'db_table': 'assunto_secao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250, null=True, unique=True)),
                ('sigla', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'divisao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DivisaoSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'divisao_secao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('secao_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('secao_nome', models.CharField(max_length=250, unique=True)),
                ('secao_sigla', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'secao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_cod', models.AutoField(primary_key=True, serialize=False)),
                ('user_nome', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_ativo', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=25)),
                ('user_bloqueado', models.CharField(choices=[('BLOQUEADO', 'BLOQUEADO'), ('DESBLOQUEADO', 'DESBLOQUEADO')], max_length=25)),
                ('user_cpf', models.CharField(max_length=25, unique=True)),
                ('user_senha', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDivisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_divisao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_secao',
                'managed': False,
            },
        ),
    ]
